#!/usr/bin/env bash

BASE_DIR="/var/www/html"

# Default SSH keys for the container
if [ ! -z "$OWNER" ]; then
    curl "https://github.com/$OWNER.keys" > $BASE_DIR/.ssh/authorized_keys
    service ssh start
    service squid start
fi
# End default SSH keys for the container

if [ ! -z "$WWWUSER" ]; then
    usermod -u $WWWUSER sail
fi

if [ ! -d /.composer ]; then
    mkdir /.composer
fi

chmod -R ugo+rw /.composer

if [ $# -gt 0 ]; then
    exec gosu $WWWUSER "$@"
else
    exec /usr/bin/supervisord -c /etc/supervisor/conf.d/supervisord.conf
fi
