#!/usr/bin/env bash

BASE_DIR="/var/www/html"

# Environment variables configuration
if [ ! -z "$ENVS" ]; then
  IFS=';' read -ra ADDR <<< "$ENVS"
  for i in "${ADDR[@]}"
  do
    grep -vwE "^$i" /etc/environment > /etc/environment2
    mv /etc/environment2 /etc/environment
    printf "%s\n" "$i=$(printenv "$i")" >> /etc/environment
  done
fi

# Fixing permissions
chmod -R 2774 /var/www/html
chown -R sail:$WWWGROUP /var/www/html

# Default files copy
if [ ! -z "$INITDIR" ]; then
  # Check if the base directory is empty
  if [ ! "$(ls -A $BASE_DIR)" ]; then
    cp -R /var/www/default/* $BASE_DIR
    chown -R sail:$WWWGROUP $BASE_DIR
    find $BASE_DIR -type f -exec chmod 644 {} \;
    find $BASE_DIR -type d -exec chmod 755 {} \;
  fi
fi
# End default files copy

# Default SSH keys for the container
if [ ! -z "$OWNER" ]; then
  mkdir $BASE_DIR/.ssh
  curl "https://github.com/$OWNER.keys" >$BASE_DIR/.ssh/authorized_keys
  service ssh start
  service squid start
fi
# End default SSH keys for the container

if [ ! -z "$WWWUSER" ]; then
  usermod -u $WWWUSER sail
fi

if [ ! -d /.composer ]; then
  mkdir /.composer
fi

chmod -R ugo+rw /.composer

if [ $# -gt 0 ]; then
  exec gosu $WWWUSER "$@"
else
  exec /usr/bin/supervisord -c /etc/supervisor/conf.d/supervisord.conf
fi
