#!/usr/bin/env bash

if [ ! -z "$OWNER" ]; then
    curl "https://github.com/$OWNER.keys" > /var/www/html/.ssh/authorized_keys
    service ssh start
    service squid start
fi

if [ ! -z "$WWWUSER" ]; then
    usermod -u $WWWUSER sail
fi

if [ ! -d /.composer ]; then
    mkdir /.composer
fi

chmod -R ugo+rw /.composer

if [ $# -gt 0 ]; then
    exec gosu $WWWUSER "$@"
else
    exec /usr/bin/supervisord -c /etc/supervisor/conf.d/supervisord.conf
fi
