---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: {{ include "apache.fullname" . }}-web-route
  annotations:
    {{- $endpoint := "dev" -}}
    {{- if .Values.project.public }}
    kubernetes.io/ingress.class: public-ingress
    {{- $endpoint = "pub" -}}
    {{- else }}
    kubernetes.io/ingress.class: private-ingress
    {{- end }}
spec:
  entryPoints:
    - websecure
  routes:
  {{- if .Values.project.username }}
    - match: Host("{{ .Values.project.name }}-{{ .Values.project.username }}.{{ $endpoint }}.codingduck.cloud")
  {{- else}}
    - match: Host("{{ .Values.project.name }}.{{ $endpoint }}.codingduck.cloud")
  {{- end}}
      kind: Rule
      services:
        - name: {{ include "apache.fullname" . }}-web
          port: 80
          kind: Service

  tls:
    {{- if .Values.project.public }}
    secretName: public-cert-secret
    {{- else }}
    secretName: private-cert-secret
    {{- end }}
---
{{- if .Values.web.ssh -}}
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRouteTCP
metadata:
  name: {{ include "apache.fullname" . }}-ssh-route
  annotations:
    kubernetes.io/ingress.class: private-ingress
spec:
  entryPoints:
    - websecure
  routes:
    {{- if .Values.project.username }}
    - match: HostSNI("{{ .Values.project.name }}-{{ .Values.project.username }}.ssh.codingduck.cloud")
    {{- else}}
    - match: HostSNI("{{ .Values.project.name }}.ssh.codingduck.cloud")
    {{- end}}
      services:
        - name: {{ include "apache.fullname" . }}-stunnel
          port: 3129
  tls:
    passthrough: true
    secretName: ssh-cert-secret
{{- end}}