{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "wordpress.serviceAccountName" . }}
  labels:
    {{- include "wordpress.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    argocd.argoproj.io/sync-wave: "1"
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
