{{- if .Values.web.ssh -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "wordpress.fullname" . }}-stunnel
  labels:
    {{- include "wordpress.labels" . | nindent 4 }}
  annotations:
    argocd.argoproj.io/sync-wave: "30"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ include "wordpress.fullname" . }}-stunnel
      {{- include "wordpress.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        app: {{ include "wordpress.fullname" . }}-stunnel
        {{- include "wordpress.selectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "wordpress.serviceAccountName" . }}
      containers:
        - name: "stunnel"
          image: "ghcr.io/codingducksrl/stunnel"
          imagePullPolicy: IfNotPresent
          env:
            - name: "SSH_HOST"
              value: {{ include "wordpress.fullname" . }}-web
          ports:
            - name: stunnel
              containerPort: 3129

{{- end -}}